---
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="server=true user=sgordon"
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="desktop=true user=sgordon"
- hosts: "*"
  remote_user: root
  roles:
      - role: common
        user: "{{user}}"
