---
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="server=true user=sgordon"
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="desktop=true user=sgordon"
- hosts: "*"
  remote_user: root
  tasks:
      # Pre-reqs
      - package: name=libselinux-python state=latest
      # Common steps
      - include: tasks/update.yaml
      - include: tasks/nested-virt-intel.yaml
      - include: tasks/virt-install.yaml
        when: desktop == "true"
      - include: tasks/docker-machine-kvm-install.yaml
        when: desktop == "true"
      # Common packages
      - package: name=vim state=latest
      - package: name=git state=latest
      - package: name=wget state=latest
      - package: name=tuned state=latest
      - service: name=tuned state=started enabled=yes
      # Desktop/laptop packages
      - package: name=ansible state=latest
        when: desktop == "true"
      - package: name=colordiff state=latest
        when: desktop == "true"
      - package: name=chkrootkit state=latest
        when: desktop == "true"
      - package: name=gitstats state=latest
        when: desktop == "true"
      - package: name=gimp state=latest
        when: desktop == "true"
      - package: name=gnome-tweak-tool state=latest
        when: desktop == "true"
      - package: name=inkscape state=latest
        when: desktop == "true"
      - package: name=mc state=latest
        when: desktop == "true"
      - package: name=python-bugzilla state=latest
        when: desktop == "true"
      - package: name=screen state=latest
        when: desktop == "true"
      - package: name=spice-xpi state=latest
        when: desktop == "true"
      - package: name=xchat state=latest
        when: desktop == "true"
      - package: name=terminator state=latest
        when: desktop == "true"
      - package: name=youtube-dl state=latest
        when: desktop == "true"
      - include: tasks/slack-install.yaml
        when: desktop == "true"
      - include: tasks/chrome-install.yaml
        when: desktop == "true"
      - include: tasks/playonlinux-install.yaml
        when: desktop == "true"
      - include: tasks/openra-install.yaml
        when: desktop == "true"
      # Download and install dotfiles
      - name: Clone environment-configuration
        git:
          repo: https://github.com/xsgordon/environment-configuration.git
          dest: /home/{{ user }}/environment-configuration
      - name: Execute environment-configuration
        shell: /home/{{ user }}/environment-configuration/install.sh
        args:
          chdir: /home/{{ user }}/environment-configuration/
        become: yes
        become_user: "{{ user }}"
