---
#   ansible-playbook -i hosts environment-configuration.yaml --tags "server" --extra-vars="user=sgordon"
#   ansible-playbook -i hosts environment-configuration.yaml --tags "desktop" --extra-vars="user=sgordon"
- hosts: "*"
  remote_user: root
  roles:
      - role: common
        user: "{{user}}"
        tags:
            - common
            - server
            - desktop
      - role: server
        user: "{{user}}"
        tags:
            - server
      - role: desktop
        user: "{{user}}"
        tags:
            - desktop
