---
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="server=true user=sgordon"
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="desktop=true user=sgordon"
- hosts: "*"
  remote_user: root
  tasks:
      # Pre-reqs
      - package: name=libselinux-python state=latest
      # Common steps
      - include: tasks/update.yaml
      - include: tasks/nested-virt-intel.yaml
      - include: tasks/virt-install.yaml
        when: desktop == "true"
      # Common packages
      - package: name=vim state=latest
      - package: name=git state=latest
      - package: name=wget state=latest
      - package: name=tuned state=latest
      - service: name=tuned state=started enabled=yes
      # Desktop/laptop packages
      - package: name=ansible state=latest
        when: desktop == "true"
      - package: name=chkrootkit state=latest
        when: desktop == "true"
      - package: name=gitstats state=latest
        when: desktop == "true"
      - package: name=gimp state=latest
        when: desktop == "true"
      - package: name=gnome-tweak-tool state=latest
        when: desktop == "true"
      - package: name=inkscape state=latest
        when: desktop == "true"
      - package: name=mc state=latest
        when: desktop == "true"
      - package: name=python-bugzilla state=latest
        when: desktop == "true"
      - package: name=screen state=latest
        when: desktop == "true"
      - package: name=spice-xpi state=latest
        when: desktop == "true"
      - package: name=xchat state=latest
        when: desktop == "true"
      - package: name=youtube-dl state=latest
        when: desktop == "true"
      - name: Enable slack repo
        yum_repository:
            name: slack
            description: slack
            baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64
            gpgkey: https://packagecloud.io/gpg.key
        when: desktop == "true"
      - package: name=slack state=latest
        when: desktop == "true"
      - lineinfile:
          dest: /usr/share/applications/slack.desktop
          regexp: "^Exec="
          line: "Exec=/usr/bin/cpulimit -l 10 /usr/bin/slack --disable-gpu %U"
        when: desktop == "true"
      # Enable google-chrome repo and install chrome
      - name: Enable chrome repo
        yum_repository:
          name: google-chrome
          description: google-chrome
          baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch/
          gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
        when: desktop == "true"
      - name: Install chrome
        package: name=google-chrome-stable state=latest
        when: desktop == "true"
      # Enable playonlinux and install playonlinux
      - name: Enable playonlinux repo
        yum_repository:
            name: playonlinux
            description: playonlinux
            baseurl: http://rpm.playonlinux.com/fedora/yum/base
            gpgkey: http://rpm.playonlinux.com/public.gpg
        when: desktop == "true"
      - name: Install playonlinux
        package: name=playonlinux state=latest
        when: desktop == "true"
      # Enable openra and install openra
      - name: Enable OpenRA repo
        yum_repository:
            name: OpenRA
            baseurl: http://download.opensuse.org/repositories/games:/openra/Fedora_26/
            gpgkey: http://download.opensuse.org/repositories/games:/openra/Fedora_26/repodata/repomd.xml.key
        when: desktop == "true"
      - name: Install OpenRA
        package: name=openra state=latest
        when: desktop == "true"
      # Download and install dotfiles
      - name: Clone environment-configuration
        git:
          repo: https://github.com/xsgordon/environment-configuration.git
          dest: /home/{{ user }}/environment-configuration
      - name: Execute environment-configuration
        shell: /home/{{ user }}/environment-configuration/install.sh
        args:
          chdir: /home/{{ user }}/environment-configuration/
        become: yes
        become_user: "{{ user }}"
