---
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="server=true user=sgordon"
#   ansible-playbook -i hosts environment-configuration.yaml --extra-vars="desktop=true user=sgordon"
- hosts: "*"
  remote_user: root
  tasks:
      # Pre-reqs
      - package: name=libselinux-python state=latest
      # Common steps
      - include: tasks/update.yaml
      - include: tasks/nested-virt-intel.yaml
      # Common packages
      - package: name=vim state=latest
      - package: name=git state=latest
      - package: name=wget state=latest
      - package: name=tuned state=latest
      - service: name=tuned state=started enabled=yes
      # Desktop specific actions
      - include: tasks/desktop-pkgs-install.yaml
        when: desktop == "true"
      # Download and install dotfiles
      - name: Clone environment-configuration
        git:
          repo: https://github.com/xsgordon/environment-configuration.git
          dest: /home/{{ user }}/environment-configuration
      - name: Execute environment-configuration
        shell: /home/{{ user }}/environment-configuration/install.sh
        args:
          chdir: /home/{{ user }}/environment-configuration/
        become: yes
        become_user: "{{ user }}"
