---
# Docker machine setup
- name: Get docker-machine KVM driver
  get_url:
    url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm
    dest: /usr/local/bin/docker-machine-driver-kvm
    mode: 0755
- user:
    name: "{{ user }}"
    append: yes
    groups: libvirt
