---
tasks:
  # Download and install dotfiles
  - name: Clone environment-configuration
    git:
      repo: https://github.com/xsgordon/environment-configuration.git
      dest: /home/{{ user }}/environment-configuration
  - name: Execute environment-configuration
    shell: /home/{{ user }}/environment-configuration/install.sh
    args:
      chdir: /home/{{ user }}/environment-configuration/
    become: yes
    become_user: "{{ user }}"
