---
- package: name=libselinux-python state=latest
  become: true
- import_tasks: update.yaml
- import_tasks: common-install.yaml
- import_tasks: nested-virt-intel.yaml
- import_tasks: virt-install.yaml
- import_tasks: dotfile-install.yaml
- import_tasks: screen.yaml
